name: ecommerce_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: ^3.5.3


#------------Packages--------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_lints: ^5.0.0


# State Management

get: ^4.6.6
get_storage: ^2.1.1


# Product Specific



#----------------- ./ Package End --------------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^5.0.0



flutter:
  uses-material-design: true



#------------------- LOCAL ASSETS --------------------------------#
  assets:
    - assets/images/on_boarding_images/
    - assets/icons/brands/
    - assets/logos/
    - assets/logos/logo_light.png
    - assets/logos/logo_dark.png

#------------------- LOCAL ASSETS --------------------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800