// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkXHJ41qGcxmE4ZkAsq8R0eT3JKqb81mU',
    appId: '1:842470878235:web:7eb9d4b8cb69fee3a75cbe',
    messagingSenderId: '842470878235',
    projectId: 'ecommerceapp-8052e',
    authDomain: 'ecommerceapp-8052e.firebaseapp.com',
    storageBucket: 'ecommerceapp-8052e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWz3gjSzvNuuy_UqtetdpRizuRdj0llig',
    appId: '1:842470878235:android:36345e29109eff79a75cbe',
    messagingSenderId: '842470878235',
    projectId: 'ecommerceapp-8052e',
    storageBucket: 'ecommerceapp-8052e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGmfQHNDOUKa0XcTB7cQcrV9PQwTur0yE',
    appId: '1:842470878235:ios:3ba8ccc008f81f75a75cbe',
    messagingSenderId: '842470878235',
    projectId: 'ecommerceapp-8052e',
    storageBucket: 'ecommerceapp-8052e.firebasestorage.app',
    androidClientId: '842470878235-gjp7ls1eeg71jqr5tskh99mjf5popkec.apps.googleusercontent.com',
    iosClientId: '842470878235-u868gdtf2bd6eqs1325tabq709gnlfe3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGmfQHNDOUKa0XcTB7cQcrV9PQwTur0yE',
    appId: '1:842470878235:ios:3ba8ccc008f81f75a75cbe',
    messagingSenderId: '842470878235',
    projectId: 'ecommerceapp-8052e',
    storageBucket: 'ecommerceapp-8052e.firebasestorage.app',
    androidClientId: '842470878235-gjp7ls1eeg71jqr5tskh99mjf5popkec.apps.googleusercontent.com',
    iosClientId: '842470878235-u868gdtf2bd6eqs1325tabq709gnlfe3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkXHJ41qGcxmE4ZkAsq8R0eT3JKqb81mU',
    appId: '1:842470878235:web:103589756840c5f4a75cbe',
    messagingSenderId: '842470878235',
    projectId: 'ecommerceapp-8052e',
    authDomain: 'ecommerceapp-8052e.firebaseapp.com',
    storageBucket: 'ecommerceapp-8052e.firebasestorage.app',
  );

}